name: Build Windows Release

on:
  push:
    branches: [ "main", "master" ] # Runs every time you push to main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qtserialport'

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build the App
        run: cmake --build build --config Release

      - name: Package with windeployqt
        run: |
          cd build/Release
          windeployqt app_Vacuumeter.exe

      - name: Upload the Zip File
        uses: actions/upload-artifact@v4
        with:
          name: Vacuumeter-Windows
          path: build/Release/